version: '3.8'
services:
  postgres:
    container_name: local-postgres
    image: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USERNAME: "root"
      POSTGRES_PASSWORD: "root"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  mongo:
    container_name: local-mongo
    image: "mongo:4.4.3"
    restart: always
    ports:
      - '27018:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=fromdb
    volumes:
      - ./mongo/data:/data/db