spring.datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: "jdbc:postgresql://127.0.0.1:5433/testdb"
    username: root
    password: root

spring.data:
    mongodb:
      host: localhost
      port: 27018
      username: "root"
      password: "root"
      database: "fromdb"
      authentication-database: admin

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true