spring:
  mongodb:
    host: localhost
    port: 27018
    base-package: fromdb
    username: root
    password: root
  postgres:
    host: localhost
    port: 5433
    dbname: todb
    dbschema: public
    username: root
    password: root
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: create

    security:
      user:
        name: user
        password: user

#spring.datasource:
#    driver-class-name: org.postgresql.Driver
#    jdbc-url: "jdbc:postgresql://127.0.0.1:5433/testdb"
#    username: root
#    password: root
#
#spring.data:
#    mongodb:
#      host: localhost
#      port: 27018
#      username: "root"
#      password: "root"
#      database: "fromdb"
#      authentication-database: admin


