spring.datasource:
  driver-class-name: org.postgresql.Driver
  jdbcUrl: "jdbc:postgresql://localhost:5433/postgres"
  username: "root"
  password: "root"

spring.data:
    mongodb:
      host: localhost
      port: 27018
      username: "root"
      password: "root"
      database: "fromdb"
      authentication-database: admin

spring:
  jpa:
    show-sql: true


